### ISSUE TITLE
help find your package

### ISSUE THREAD

**Issue by Scrum** [posthtml/posthtml-insert-at#2]
@renyamizuno Hi, I am a posthtml package maintainer, I found your package because you have a posthtml package in dependencies. I think it will be easier for people to find your package if you add it to the list of plugins [here](https://github.com/posthtml/posthtml#plugins) and [here](https://github.com/posthtml/posthtml-plugins/), and of course the first thing to do in the posthtml organization itself - I can move your package to the posthtml organization for more popularity, for this it will be necessary to add me to this repository as owner and then I will transfer it to posthtml organization. The package itself will remain under your control.

let me know about any decision you make, i will understand if you are not interested

**Comment by metonym** [comment]
@Scrum I'll assume the autocomplete switched the user id "@ **me**tonym" with "@ **me**rotan."  This plugin is already listed in `posthtml-plugins`.

However, I would be more than happy to transfer it to the PostHTML organization.

**Comment by metonym** [comment]
I've added you as a collaborator.

**Comment by Scrum** [comment]
@metonym Thanks but unfortunately this is not enough to move - I do not have access to the `settings` - for this I must be `owner`

**Comment by metonym** [comment]
@Scrum Understood. I've initiated the transfer.

**Comment by Scrum** [comment]
@metonym Check access rights to this repository. Welcome aboard.

**Comment by metonym** [comment]
Thanks!
