### ISSUE TITLE
Not working with multiple classes

### ISSUE THREAD

**Issue by Drarig29** [posthtml/posthtml-insert-at#37]
The following code doesn't work:

```js
const posthtml = require('posthtml');
const { insertAt } = require('posthtml-insert-at');

const html = '<div class="foo bar" />';
 
posthtml()
  .use(
    insertAt({
      selector: '.foo',
      append: '<a>example</a>',
      behavior: 'inside'
    })
  )
  .process(html)
  .then(result => console.log(result.html));
```

It works when the input HTML **and** the selector have only one class but as soon as we request only one class although there are multiple classes in the input, it doesn't work anymore.

I don't know if this is related to you saying that "currently, this plugin does not supported nested selectors".

**Comment by metonym** [comment]
@Drarig29 This is unexpected. I think this would solved by using a more robust selector matcher like https://github.com/posthtml/posthtml-match-helper.

**Comment by metonym** [comment]
@Drarig29 A fix has been published in version 0.2.7.

Could you please try it out and LMK if there are any issues?

**Comment by Drarig29** [comment]
Thank you, it works!

**Comment by metonym** [comment]
Great – thank you for raising this issue.
